from __future__ import annotations

from pathlib import Path
from typing import List, Tuple, Literal


def export_grbl_standard(
    points: List[Tuple[float, float, float, int]],
    output_path: str,
    dwell_s: float = 0.08,
    feed_rate: float = 500.0,
) -> str:
    """
    Export to standard GRBL G-code format.
    Suitablefor Arduino + CNC Shield with PWM vibration motor.
    """
    lines: List[str] = [
        "; Generated by Stone Halftone Engraver",
        "; PWM Vibration Motor Control",
        "; DO NOT MODIFY - Use GUI or CLI to regenerate",
        "; ",
        "G21 ; millimeters",
        "G90 ; absolute positioning",
        "G92 X0 Y0 ; set origin",
        "; Start engraving",
    ]

    point_count = 0
    for x_mm, y_mm, radius_mm, pwm_value in points:
        if radius_mm <= 0.05:
            continue
        point_count += 1
        lines.append(f"G0 X{x_mm:.3f} Y{y_mm:.3f} ; move to point {point_count}")
        lines.append(f"M3 S{pwm_value} ; vibrate at PWM {pwm_value} (0-255)")
        lines.append(f"G4 P{dwell_s:.3f} ; dwell {int(dwell_s * 1000)}ms")
        lines.append("M5 ; stop vibration")

    lines.extend([
        "; End engraving",
        "G0 X0 Y0 ; return to origin",
        "M5 ; ensure motor is off",
        "M2 ; end program",
    ])

    gcode = "\n".join(lines) + "\n"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(gcode, encoding="utf-8")
    return gcode


def export_modbus_rtu(
    points: List[Tuple[float, float, float, int]],
    output_path: str,
    slave_id: int = 1,
    register_base: int = 100,
) -> str:
    """
    Export to ModBus RTU format for industrial PLC controllers.
    Each point sends: X, Y, PWM via ModBus registers.
    """
    lines: List[str] = [
        "; ModBus RTU Format - Stone Halftone Engraver",
        "; Slave ID: {}",
        "; Register Base: {}",
        ";",
    ]

    lines[1] = lines[1].format(slave_id)
    lines[2] = lines[2].format(register_base)

    point_count = 0
    reg = register_base
    for x_mm, y_mm, radius_mm, pwm_value in points:
        if radius_mm <= 0.05:
            continue
        point_count += 1
        x_int = int(x_mm * 1000)  # Convert to microns as integer
        y_int = int(y_mm * 1000)

        lines.append(f"; Point {point_count}")
        lines.append(f"WRITE_REGISTER {slave_id} {reg} {x_int} ; X position")
        lines.append(f"WRITE_REGISTER {slave_id} {reg + 1} {y_int} ; Y position")
        lines.append(f"WRITE_REGISTER {slave_id} {reg + 2} {pwm_value} ; PWM value")
        lines.append(f"WRITE_COIL {slave_id} {reg + 3} 1 ; trigger motion")
        lines.append("; Wait for completion signal")
        reg += 4

    lines.extend([
        "; End sequence",
        f"WRITE_COIL {slave_id} {reg} 0 ; disable motion",
    ])

    content = "\n".join(lines) + "\n"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    return content


def export_csv_data(
    points: List[Tuple[float, float, float, int]],
    output_path: str,
) -> str:
    """
    Export to CSV format for data analysis or custom processing.
    Format: X,Y,Radius,PWM,Intensity%
    """
    lines: List[str] = [
        "PointID,X_mm,Y_mm,Radius_mm,PWM_0_255,Intensity_Percent",
    ]

    point_count = 0
    for x_mm, y_mm, radius_mm, pwm_value in points:
        if radius_mm <= 0.05:
            continue
        point_count += 1
        intensity = (pwm_value / 255.0) * 100.0
        lines.append(f"{point_count},{x_mm:.3f},{y_mm:.3f},{radius_mm:.3f},{pwm_value},{intensity:.1f}")

    content = "\n".join(lines) + "\n"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    return content


def export_json_data(
    points: List[Tuple[float, float, float, int]],
    output_path: str,
) -> str:
    """
    Export to JSON format for web-based viewers or APIs.
    """
    import json

    data = {
        "format": "Stone Halftone Engraver",
        "version": "1.0",
        "points_count": sum(1 for x, y, r, p in points if r > 0.05),
        "points": [
            {
                "id": i,
                "x_mm": x,
                "y_mm": y,
                "radius_mm": round(r, 3),
                "pwm": p,
                "intensity_percent": round((p / 255.0) * 100.0, 1),
            }
            for i, (x, y, r, p) in enumerate(
                [(x, y, r, p) for x, y, r, p in points if r > 0.05], 1
            )
        ],
    }

    content = json.dumps(data, indent=2, ensure_ascii=False)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    return content


def export_matlab_script(
    points: List[Tuple[float, float, float, int]],
    output_path: str,
) -> str:
    """
    Export to MATLAB script for trajectory analysis and visualization.
    """
    lines: List[str] = [
        "% Stone Halftone Engraver - MATLAB Data",
        "% Generated script for trajectory analysis",
        "%",
        "clear all; close all; clc;",
        "%",
    ]

    # Data arrays
    x_vals = []
    y_vals = []
    pwm_vals = []
    radius_vals = []

    for x_mm, y_mm, radius_mm, pwm_value in points:
        if radius_mm > 0.05:
            x_vals.append(x_mm)
            y_vals.append(y_mm)
            pwm_vals.append(pwm_value)
            radius_vals.append(radius_mm)

    # Convert to MATLAB format
    x_str = "[" + " ".join(f"{x:.3f}" for x in x_vals) + "];"
    y_str = "[" + " ".join(f"{y:.3f}" for y in y_vals) + "];"
    pwm_str = "[" + " ".join(f"{p}" for p in pwm_vals) + "];"
    radius_str = "[" + " ".join(f"{r:.3f}" for r in radius_vals) + "];"

    lines.extend([
        f"X = {x_str}",
        f"Y = {y_str}",
        f"PWM = {pwm_str}",
        f"Radius = {radius_str}",
        "%",
        "% Plot trajectory",
        "figure('Name', 'Halftone Engraving Path');",
        "scatter(X, Y, 30, PWM, 'filled', 'MarkerFaceAlpha', 0.7);",
        "colorbar('Label', 'PWM Value (0-255)');",
        "xlabel('X (mm)'); ylabel('Y (mm)');",
        "title('Stone Halftone Engraving Trajectory');",
        "grid on; axis equal;",
        "%",
        "% Plot PWM distribution",
        "figure('Name', 'PWM Intensity Distribution');",
        "histogram(PWM, 50, 'FaceColor', 'blue', 'FaceAlpha', 0.7);",
        "xlabel('PWM Value (0-255)'); ylabel('Frequency');",
        "title('PWM Vibration Intensity Distribution');",
        "grid on;",
        "%",
        f"fprintf('Total engraving points: %d\\n', length(X));",
        f"fprintf('Average PWM: %.1f\\n', mean(PWM));",
        f"fprintf('Min PWM: %d, Max PWM: %d\\n', min(PWM), max(PWM));",
    ])

    content = "\n".join(lines) + "\n"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    return content


def export_gcode(
    points: List[Tuple[float, float, float, int]],
    output_path: str,
    format_type: Literal["grbl", "modbus", "csv", "json", "matlab"] = "grbl",
    **kwargs,
) -> str:
    """
    Universal exporter supporting multiple formats.
    
    Args:
        points: List of (x, y, radius, pwm) tuples
        output_path: Output file path
        format_type: Export format - grbl, modbus, csv, json, or matlab
        **kwargs: Format-specific options
    
    Returns:
        Exported content as string
    """
    exporters = {
        "grbl": export_grbl_standard,
        "modbus": export_modbus_rtu,
        "csv": export_csv_data,
        "json": export_json_data,
        "matlab": export_matlab_script,
    }

    if format_type not in exporters:
        raise ValueError(f"Unknown format: {format_type}. Choose from: {', '.join(exporters.keys())}")

    exporter = exporters[format_type]
    return exporter(points, output_path, **kwargs)


if __name__ == "__main__":
    # Example usage
    from stone_halftone import build_halftone_points, adjust_image

    sample_image = "sample/test.png"
    points = build_halftone_points(
        adjust_image(sample_image),
        cell_size_mm=3.0,
        tool_diameter_mm=1.2,
    )

    # Export to multiple formats
    export_gcode(points, "output/test_grbl.nc", format_type="grbl")
    export_gcode(points, "output/test_data.csv", format_type="csv")
    export_gcode(points, "output/test_data.json", format_type="json")
    export_gcode(points, "output/test_analysis.m", format_type="matlab")

    print("✓ Exported to GRBL, CSV, JSON, and MATLAB formats")
